Parameters:
  AccountAID:
    Description: Acccount A's ID (Make sure that you upload template_a in this account)  
    Type: String

  AccountBID:
    Description: Acccount B's ID (Make sure that you upload template_b in this account)  
    Type: String   


Resources:
  GrantAdminRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: role-for-admin-access
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow 
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub 
                - arn:aws:iam::${acc_a_id}:user/Clark
                - acc_a_id: !Ref AccountAID
      Policies: 
        - PolicyName: admin-access-policy
          PolicyDocument: 
            Statement: 
              - Effect: Allow
                Action: "*"
                Resource: "*"

  ReadOnlyRoleS3:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: s3-read-only-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal: 
              AWS: !Sub 
                - arn:aws:iam::${acc_a_id}:user/Bruce
                - acc_a_id: !Ref AccountAID
      Policies:
        - PolicyName: s3-read-only-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                Resource: 
                  - arn:aws:s3:::task-bucket-account-c
                  - arn:aws:s3:::task-bucket-account-c/*  

  WriteOnlyRoleS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: s3-write-only-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal: 
              AWS: !Sub 
                - arn:aws:iam::${acc_b_id}:role/bat-license-to-put
                - acc_b_id: !Ref AccountBID
      Policies:
        - PolicyName: s3-write-only-policy
          PolicyDocument: 
            Statement:
              - Effect: Allow
                Action: 
                  - s3:Put*
                  - s3:List*
                Resource: 
                  - arn:aws:s3:::task-bucket-account-c  
                  - arn:aws:s3:::task-bucket-account-c/*  

  TaskBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: task-bucket-account-c

Outputs:
  AdminRole:
    Description: Name of role which grants admin permissions to Clark
    Value: !Ref GrantAdminRole

  ReadOnlyS3:
    Description: Name of role which grants s3 bucket read only permissions to Bruce
    Value: !Ref ReadOnlyRoleS3

  WriteOnlyS3:
    Description: Name of the role which grants s3 bucket write only permissions to role bat-license-to-put
    Value: !Ref WriteOnlyRoleS3  
    
  BucketName:
    Description: Name of the s3 bucket
    Value: !Ref TaskBucket